stages:
  - build
  - test
  - deploy-dev
  - deploy-k8
  - deploy-prod

build-job:
  tags:
    - AadharIdfyUAT
  stage: build

  script:
    - echo "Hello gitlab User, $GITLAB_USER_LOGIN!"
    - echo "Hello System-user, $USER"
    - echo "$DeploymentType"

  artifacts:
   name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
   paths:
    - ./
   expire_in: 1 week


test-job1:
  tags:
   - AadharIdfyUAT
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  tags:
   - AadharIdfyUAT
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"

#new-script-job:
 # tags:
   # - k8suat
  #stage: test
  #script:
   # - echo "This job runs a new script with a different runner tag."
  #  - bash deploy/k8-deploy.sh
 # only:
 #   -  DevRelease

deploy-job-dev:
  tags:
    - AadharIdfyUAT
  stage: deploy-dev

      
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - bash deploy/deploy.sh

  only:
    -  DevRelease





deploy-job-prod:
  tags:
    - ProdRelease
  stage: deploy-prod
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  only:
    - ProdRelease
