import os
from dotenv import load_dotenv

load_dotenv()

Super_Agent_Mobile_Number = '70422 00362'
REJECT_MAIL_SUBJECT = "FIA Video KYC Rejection"
VIDEO_KYC_RESEND_SUB_AGENT = 'Notification: Video KYC New Link'

# List of required environment variables
required_env_vars = ['MONGO_URI', 'FIN_API_KEY', 'FIN_ACCOUNT_ID', 'FIN_KEY_ID', 'FIN_SECRET_BASE64', 'FIN_OU_ID', 'FIN_CALLBACK_URL', 'IDFY_BASE_URL' ,
        'IDFY_AADHAR_URL', 'IDFY_PANCARD_URL', 'IDFY_CONFIG_ID', 'IDFY_PRO_URL', 'IDFY_PRO_ID_URL', 'PRO_API_KEY', 'PRO_ACCOUNT_ID', 'VID_SMTP_SERVER',
        'VID_SMTP_PORT', 'VID_SENDER_EMAIL', 'VID_SENDER_PASSWORD', 'AGENT_CODE_AUTO_URL', 'AES_ENCRYPT_SECRET_KEY', 'AWS_ACCESS_KEY_ID',  'AWS_SECRET_ACCESS_KEY',
        'AWS_S3_BUCKET_NAME', 'MONGO_DB_NAME', 'POSTGRESQL_LOG_USERNAME' ,'POSTGRESQL_LOG_PASSWORD', 'POSTGRESQL_LOG_HOST',  'POSTGRESQL_LOG_PORT', 'POSTGRESQL_LOG_DATABASE']

# Check all required environment variables
for var in required_env_vars:
    if os.getenv(var) is None:
        raise ValueError(f"No value found for environment variable '{var}'")

AADHAR_URL = os.getenv("IDFY_AADHAR_URL")
PANCARD_URL = os.getenv("IDFY_PANCARD_URL")
REQUEST_SEND_URL = os.getenv("IDFY_BASE_URL")
PROFILE_URL = os.getenv("IDFY_PRO_URL")
AES_ENCRYPT_SECRET_KEY = os.getenv('AES_ENCRYPT_SECRET_KEY')
MONGO_URI = os.getenv('MONGO_URI')
FIN_CALLBACK_URL = os.getenv('FIN_CALLBACK_URL')
PRO_API_KEY = os.getenv("PRO_API_KEY")
PRO_ACCOUNT_ID = os.getenv("PRO_ACCOUNT_ID")
VID_SMTP_SERVER = os.getenv('VID_SMTP_SERVER')
VID_SMTP_PORT = os.getenv('VID_SMTP_PORT')
VID_SENDER_EMAIL = os.getenv('VID_SENDER_EMAIL')
VID_SENDER_PASSWORD = os.getenv('VID_SENDER_PASSWORD')
FIN_ACCOUNT_ID = os.getenv("FIN_ACCOUNT_ID")
FIN_API_KEY = os.getenv("FIN_API_KEY")
FIN_KEY_ID = os.getenv('FIN_KEY_ID')
FIN_OU_ID = os.getenv('FIN_OU_ID')
FIN_SECRET_BASE64 = os.getenv('FIN_SECRET_BASE64')
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_S3_BUCKET_NAME = os.getenv('AWS_S3_BUCKET_NAME')
AGENT_CODE_AUTO_URL = os.getenv('AGENT_CODE_AUTO_URL')
DB_CLIENT = os.getenv('MONGO_DB_NAME')

POSTGRESQL_LOG_USERNAME = os.environ.get('POSTGRESQL_LOG_USERNAME')
POSTGRESQL_LOG_PASSWORD = os.environ.get('POSTGRESQL_LOG_PASSWORD')
POSTGRESQL_LOG_HOST     = os.environ.get('POSTGRESQL_LOG_HOST')
POSTGRESQL_LOG_PORT     = os.environ.get('POSTGRESQL_LOG_PORT')
POSTGRESQL_LOG_DATABASE = os.environ.get('POSTGRESQL_LOG_DATABASE')

SERVICE_VENDOR = os.environ.get('SERVICE_VENDOR')
AADHAAR_OTP_SENT_URL = os.getenv("AADHAAR_OTP_SENT_URL")
AADHAAR_OTP_SUBMIT_URL = os.getenv("AADHAAR_OTP_SUBMIT_URL")
CUSTOMER_ID = os.getenv("CUSTOMER_ID")
PRIVATE_API_KEY = os.getenv("PRIVATE_API_KEY")
BHARAT_PAN_VERIFY_URL = os.getenv("BHARAT_PAN_VERIFY_URL")
BHARAT_BANK_ACCOUNT_VERIFY_PENNYLESS=os.getenv("BHARAT_BANK_ACCOUNT_VERIFY_PENNYLESS")
BANK_ACCOUNT_PENNYDROP_SEND_URL=os.getenv("BANK_ACCOUNT_PENNYDROP_SEND_URL")
BANK_ACCOUNT_PENNYDROP_GET_STATUS_URL=os.getenv("BANK_ACCOUNT_PENNYDROP_GET_STATUS_URL")
